---
- set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
- name: UPGRADE ROUTER FIRMWARE
  hosts: cisco_w2950
  connection: network_cli
  gather_facts: no
  
  vars:
    compliant_ios_version: {{hostvars[inventory_hostname].version}}
    roles:
      - ios_upgrade

  